/**
 * Gen API — generated client, v3.2.1.
 *
 * Generated by `angus client`. Do not edit: regenerate instead.
 * Self-contained — no runtime dependencies.
 */

/* eslint-disable */

/** Named `Error` in the API; renamed to avoid a clash. */
export interface ErrorModel {
  error: string
  detail: string
  code?: string
  /** Field name to the problems with it. */
  errors?: Record<string, string[]>
}

export interface Gizmo {
  id: number
  name: string
  price: number
  status: "draft" | "live"
  note: string | null
}

export interface GizmoInput {
  name: string
  price?: number
  status?: "draft" | "live"
  note?: string | null
}

export interface GizmoPatch {
  name?: string
  price?: number
  status?: "draft" | "live"
  note?: string | null
}

export interface ClientOptions {
  /** Base URL of the API, without a trailing slash. */
  baseUrl?: string
  /** Sent on every request. A function is called per request, for tokens that rotate. */
  headers?: Record<string, string> | (() => Record<string, string> | Promise<Record<string, string>>)
  /** Swap in a custom fetch — for retries, tracing, or a test double. */
  fetch?: typeof fetch
  /** Sends cookies on cross-origin requests. */
  credentials?: RequestCredentials
  /** Last chance to adjust the outgoing request. */
  onRequest?: (request: Request) => Request | Promise<Request>
  /** Observes every response, including failures. */
  onResponse?: (response: Response) => void | Promise<void>
}

/** Thrown for any non-2xx response. Carries the API's error contract. */
export class ApiError extends Error {
  readonly status: number
  readonly code: string
  readonly detail: string
  /** Field name to the problems with it, on a validation failure. */
  readonly errors?: Record<string, string[]>
  readonly response: Response

  constructor(response: Response, body: unknown) {
    const shaped = (body ?? {}) as { error?: string; detail?: string; code?: string; errors?: Record<string, string[]> }
    super(shaped.detail ?? `Request failed with status ${response.status}`)
    this.name = shaped.error ?? 'ApiError'
    this.status = response.status
    this.code = shaped.code ?? 'unknown'
    this.detail = shaped.detail ?? this.message
    this.errors = shaped.errors
    this.response = response
  }

  /** True when the failure is the caller's to fix. */
  get isClientError(): boolean {
    return this.status >= 400 && this.status < 500
  }
}

export interface RequestOptions {
  headers?: Record<string, string>
  signal?: AbortSignal
}

interface CallInput {
  params?: Record<string, string | number>
  query?: Record<string, unknown>
  body?: unknown
}

async function call<T>(
  options: ClientOptions,
  method: string,
  template: string,
  input: CallInput,
  perCall: RequestOptions,
): Promise<T> {
  const doFetch = options.fetch ?? globalThis.fetch

  let path = template
  for (const [key, value] of Object.entries(input.params ?? {})) {
    path = path.replace(`{${key}}`, encodeURIComponent(String(value)))
  }

  const search = new URLSearchParams()
  for (const [key, value] of Object.entries(input.query ?? {})) {
    if (value === undefined || value === null) continue
    if (Array.isArray(value)) for (const entry of value) search.append(key, String(entry))
    else search.set(key, String(value))
  }

  const base = (options.baseUrl ?? '').replace(/\/$/, '')
  const url = `${base}${path}${search.size > 0 ? `?${search}` : ''}`

  const configured = typeof options.headers === 'function' ? await options.headers() : (options.headers ?? {})
  const headers: Record<string, string> = { ...configured, ...perCall.headers }
  if (input.body !== undefined) headers['content-type'] ??= 'application/json'

  let outgoing = new Request(url, {
    method,
    headers,
    credentials: options.credentials,
    signal: perCall.signal,
    body: input.body === undefined ? undefined : JSON.stringify(input.body),
  })
  if (options.onRequest) outgoing = await options.onRequest(outgoing)

  const response = await doFetch(outgoing)
  await options.onResponse?.(response)

  if (response.status === 204 || response.headers.get('content-length') === '0') {
    if (!response.ok) throw new ApiError(response, undefined)
    return undefined as T
  }

  const text = await response.text()
  let body: unknown
  try {
    body = text === '' ? undefined : JSON.parse(text)
  } catch {
    body = text
  }

  if (!response.ok) throw new ApiError(response, body)
  return body as T
}

export function createClient(options: ClientOptions) {
  const config = options

  return {
    /**
     * Create a genGizmo
     */
    genGizmoCreate: (input: {
      body: GizmoInput
    }, init: RequestOptions = {}): Promise<Gizmo> =>
      call<Gizmo>(config, "POST", "/api/gizmos", (input ?? {}) as any, init),

    /**
     * Delete a genGizmo
     */
    genGizmoDestroy: (input: {
      params: { id: number }
    }, init: RequestOptions = {}): Promise<void> =>
      call<void>(config, "DELETE", "/api/gizmos/{id}", (input ?? {}) as any, init),

    /**
     * Retrieve a genGizmo
     */
    genGizmoDetail: (input: {
      params: { id: number }
    }, init: RequestOptions = {}): Promise<Gizmo> =>
      call<Gizmo>(config, "GET", "/api/gizmos/{id}", (input ?? {}) as any, init),

    /**
     * List genGizmos
     */
    genGizmoList: (input?: Record<string, never>, init: RequestOptions = {}): Promise<Gizmo[]> =>
      call<Gizmo[]>(config, "GET", "/api/gizmos", (input ?? {}) as any, init),

    /**
     * Update part of a genGizmo
     */
    genGizmoPartialUpdate: (input: {
      params: { id: number }
      body: GizmoPatch
    }, init: RequestOptions = {}): Promise<Gizmo> =>
      call<Gizmo>(config, "PATCH", "/api/gizmos/{id}", (input ?? {}) as any, init),

    /**
     * Replace a genGizmo
     */
    genGizmoUpdate: (input: {
      params: { id: number }
      body: GizmoInput
    }, init: RequestOptions = {}): Promise<Gizmo> =>
      call<Gizmo>(config, "PUT", "/api/gizmos/{id}", (input ?? {}) as any, init),

    /**
     * Health ping
     */
    ping: (input?: Record<string, never>, init: RequestOptions = {}): Promise<{
  pong: boolean
}> =>
      call<{
  pong: boolean
}>(config, "GET", "/api/ping", (input ?? {}) as any, init),

  }
}

export type Client = ReturnType<typeof createClient>
