/**
 * What an agent can read before it acts.
 *
 * Tools answer "what may I do"; they say very little about the shape of the
 * data behind them. An agent that can only call tools has to learn the domain
 * by trying things, which on a write endpoint means learning by causing
 * failures — and on a system with side effects, by causing worse than failures.
 *
 * Resources close that gap: the model list, each model's fields with their
 * types and constraints, and the OpenAPI document. All three are generated from
 * the same declarations the server runs on, so what the agent reads is what the
 * API will actually enforce.
 */

import type { FieldSpec } from '../db/fields.ts'
import type { AnyModel } from '../db/model.ts'
import type { RouteDefinition } from '../routing/router.ts'

export interface Resource {
  uri: string
  name: string
  title?: string
  description?: string
  mimeType: string
  /** Produced on read rather than up front — most are never asked for. */
  read: () => string | Promise<string>
}

export interface ResourceContents {
  uri: string
  mimeType: string
  text: string
}

/** What `resources/list` returns — the reader is not serialisable. */
export function toResourceDefinition(resource: Resource): Omit<Resource, 'read'> {
  const { read: _read, ...definition } = resource
  return definition
}

/**
 * Describes a model the way someone writing against it would want it described.
 *
 * Deliberately not the Drizzle table or the raw `FieldSpec`: both carry
 * internals that mean nothing to a caller, and an agent reading a field it
 * cannot set is being invited to try.
 */
function describeModel(model: AnyModel): unknown {
  const fields = Object.entries(model.fields).map(([name, field]) => {
    // The IR lives on `.spec`; the field wrapper around it is a type-layer
    // device, and the same unwrapping the serializer does.
    const spec = (field as { spec: FieldSpec }).spec

    return {
      name,
      kind: spec.kind,
      // The distinction an agent gets wrong first. A value is required only
      // when the caller is the one who has to supply it: not nullable, not
      // defaulted, not generated by the database, and actually writable.
      required: spec.editable && !spec.null && !spec.blank && !spec.hasDefault && !spec.auto,
      nullable: spec.null,
      ...(spec.editable ? {} : { readOnly: true }),
      ...(spec.maxLength === undefined ? {} : { maxLength: spec.maxLength }),
      ...(spec.minLength === undefined ? {} : { minLength: spec.minLength }),
      ...(spec.min === undefined ? {} : { min: spec.min }),
      ...(spec.max === undefined ? {} : { max: spec.max }),
      ...(spec.choices ? { choices: spec.choices } : {}),
      ...(spec.unique ? { unique: true } : {}),
      ...(spec.helpText ? { description: spec.helpText } : {}),
      // The target matters more than the column: it tells the agent which
      // other resource to go and read.
      ...(spec.to ? { relatesTo: spec.to().name } : {}),
    }
  })

  return {
    name: model.name,
    table: model.meta.tableName,
    primaryKey: model.pk,
    verboseName: model.meta.verboseName,
    ordering: model.meta.ordering ?? [],
    fields,
  }
}

export interface ResourceOptions {
  models: AnyModel[]
  routes: RouteDefinition[]
  openapi?: () => unknown
  /** Extra resources — a domain glossary, an operations runbook. */
  extra?: Resource[]
}

/**
 * Builds the resource set for a project.
 *
 * URIs are `angus://` rather than `file://` because none of this is a file:
 * every one is generated from the running declarations, and pointing an agent
 * at a path that does not exist would be worse than no URI at all.
 */
export function buildResources(options: ResourceOptions): Resource[] {
  const resources: Resource[] = []

  resources.push({
    uri: 'angus://models',
    name: 'models',
    title: 'Data model',
    description:
      'Every model in this application, with its fields, types, constraints and relations. ' +
      'Read this before constructing a request body.',
    mimeType: 'application/json',
    read: () => JSON.stringify(options.models.map(describeModel), null, 2),
  })

  for (const model of options.models) {
    resources.push({
      uri: `angus://models/${model.name}`,
      name: model.name,
      title: `${model.meta.verboseName} model`,
      description: `Fields, types and constraints for ${model.name}.`,
      mimeType: 'application/json',
      read: () => JSON.stringify(describeModel(model), null, 2),
    })
  }

  if (options.openapi) {
    const openapi = options.openapi
    resources.push({
      uri: 'angus://openapi',
      name: 'openapi',
      title: 'OpenAPI document',
      description: 'The full HTTP contract, including schemas the tools summarise.',
      mimeType: 'application/json',
      read: () => JSON.stringify(openapi(), null, 2),
    })
  }

  resources.push({
    uri: 'angus://routes',
    name: 'routes',
    title: 'Route table',
    description: 'Every endpoint, with its method, path and the permissions guarding it.',
    mimeType: 'application/json',
    read: () =>
      JSON.stringify(
        options.routes.map((route) => ({
          method: route.method.toUpperCase(),
          path: route.path,
          name: route.name,
          summary: route.summary,
          // Named, not described: knowing a route is guarded is useful, knowing
          // exactly how would be a map of what to attack.
          guarded: (route.permissions?.length ?? 0) > 0,
        })),
        null,
        2,
      ),
  })

  return [...resources, ...(options.extra ?? [])]
}

/** Reads one resource by URI, or explains that it does not exist. */
export async function readResource(resources: Resource[], uri: string): Promise<ResourceContents> {
  const resource = resources.find((candidate) => candidate.uri === uri)
  if (!resource) throw new Error(`Unknown resource: ${uri}`)

  return { uri, mimeType: resource.mimeType, text: await resource.read() }
}
