/**
 * `makemigrations` and `migrate`.
 *
 * angusjs doesn't implement a migration engine — drizzle-kit already diffs a
 * schema against the migration history and emits SQL. What's missing is the
 * bridge: drizzle-kit wants a module exporting table objects, and our tables
 * only exist once a dialect is known. So `makemigrations` generates that module
 * from the project's models, then hands over.
 */

import { mkdir, rm } from 'node:fs/promises'
import { relative, resolve } from 'node:path'
import { appModels } from '../../core/app.ts'
import type { LoadedProject } from '../../core/config.ts'
import { resolveSettings } from '../../core/settings.ts'
import type { AnyModel } from '../../db/model.ts'
import type { Dialect } from '../../db/schema.ts'
import { dim, fail, info, success, warn } from '../ui.ts'

/** drizzle-kit spells the Postgres dialect differently to our config. */
const KIT_DIALECT: Record<Dialect, string> = {
  sqlite: 'sqlite',
  postgres: 'postgresql',
}

const GENERATED_DIR = '.angus'

function assertDatabase(project: LoadedProject): { dialect: Dialect; url: string } {
  const database = project.settings.database
  if (!database) {
    throw new Error(
      'No `database` in your settings. Add one to angus.config.ts:\n' +
        "  database: { dialect: 'sqlite', url: 'db.sqlite' }",
    )
  }
  return { dialect: database.dialect, url: database.url }
}

/**
 * Writes `.angus/schema.ts`, a module that rebuilds the project's Drizzle
 * tables for drizzle-kit to read. Regenerated on every run, never edited.
 */
async function writeSchemaModule(project: LoadedProject, models: AnyModel[], dialect: Dialect): Promise<string> {
  const generatedDir = resolve(project.root, GENERATED_DIR)
  await mkdir(generatedDir, { recursive: true })

  const schemaPath = resolve(generatedDir, 'schema.ts')
  const configImport = `../${relative(project.root, project.configPath)}`.replaceAll('\\', '/')

  // Exports have to be static bindings — drizzle-kit reads the module's
  // exported values, so a dynamic map wouldn't be visible to it.
  const exports = models
    .map((model) => `export const ${model.name} = tables[${JSON.stringify(model.name)}]!`)
    .join('\n')

  const source = `// Generated by \`angus makemigrations\`. Do not edit — your changes will be overwritten.
// This module exists so drizzle-kit can see the tables your models describe.
import { appModels } from 'angusjs'
import { buildSchemaExports } from 'angusjs/db'
import settings from ${JSON.stringify(configImport)}

const tables = buildSchemaExports(appModels(settings.apps), ${JSON.stringify(dialect)})

${exports}
`

  await Bun.write(schemaPath, source)
  return schemaPath
}

async function writeKitConfig(project: LoadedProject, dialect: Dialect, migrationsDir: string): Promise<string> {
  const configPath = resolve(project.root, GENERATED_DIR, 'drizzle.config.ts')

  // No credentials here: `generate` diffs against the migration folder, not a
  // live database, so there's nothing to leak into a generated file.
  const source = `// Generated by \`angus makemigrations\`. Do not edit.
import { defineConfig } from 'drizzle-kit'

export default defineConfig({
  dialect: ${JSON.stringify(KIT_DIALECT[dialect])},
  schema: './.angus/schema.ts',
  out: ${JSON.stringify(`./${migrationsDir}`)},
})
`

  await Bun.write(configPath, source)
  return configPath
}

export async function makemigrations(project: LoadedProject, args: string[]): Promise<number> {
  const { dialect } = assertDatabase(project)
  const settings = resolveSettings(project.settings)
  const models = appModels(settings.apps)

  if (models.length === 0) {
    warn('No models found. Did you list them in your app\'s `models` option?')
    return 0
  }

  await writeSchemaModule(project, models, dialect)
  const kitConfig = await writeKitConfig(project, dialect, settings.migrationsDir)

  const nameIndex = args.indexOf('--name')
  const name = nameIndex !== -1 ? args[nameIndex + 1] : args.find((arg) => !arg.startsWith('-'))

  info(`Inspecting ${models.length} model${models.length === 1 ? '' : 's'}: ${models.map((m) => m.name).join(', ')}`)

  const command = [
    'bunx',
    'drizzle-kit',
    'generate',
    '--config',
    relative(project.root, kitConfig),
    ...(name ? ['--name', name] : []),
  ]

  const proc = Bun.spawn(command, { cwd: project.root, stdout: 'inherit', stderr: 'inherit' })
  const status = await proc.exited

  if (status !== 0) {
    fail('drizzle-kit could not generate the migration.')
    info(dim('  Is drizzle-kit installed? `bun add -d drizzle-kit`'))
    return status
  }

  success(`Migrations written to ${settings.migrationsDir}/`)
  info(dim('  Review the SQL, then apply it with `angus migrate`.'))
  return 0
}

export async function migrate(project: LoadedProject): Promise<number> {
  const { dialect, url } = assertDatabase(project)
  const settings = resolveSettings(project.settings)
  const migrationsFolder = resolve(project.root, settings.migrationsDir)

  if (!(await Bun.file(resolve(migrationsFolder, 'meta/_journal.json')).exists())) {
    warn(`No migrations in ${settings.migrationsDir}/. Run \`angus makemigrations\` first.`)
    return 0
  }

  info(`Applying migrations to ${dim(url)}`)

  if (dialect === 'sqlite') {
    const { Database } = await import('bun:sqlite')
    const client = new Database(url)
    client.exec('PRAGMA foreign_keys = ON')
    const { drizzle } = await import('drizzle-orm/bun-sqlite')
    const { migrate: apply } = await import('drizzle-orm/bun-sqlite/migrator')
    apply(drizzle(client), { migrationsFolder })
    client.close()
  } else {
    const { SQL } = await import('bun')
    const client = new SQL({ url })
    const { drizzle } = await import('drizzle-orm/bun-sql')
    const { migrate: apply } = await import('drizzle-orm/bun-sql/migrator')
    await apply(drizzle(client), { migrationsFolder })
    await client.close()
  }

  success('Database is up to date.')
  return 0
}

/** Removes the generated bridge files. */
export async function cleanGenerated(project: LoadedProject): Promise<void> {
  await rm(resolve(project.root, GENERATED_DIR), { recursive: true, force: true })
}
